### ISSUE TITLE
Vault keep trying to delete a ServiceAccount from a deleted Google Project

### ISSUE THREAD

**Issue by primeroz** [hashicorp/vault-plugin-secrets-gcp#80] opened 2020-03-20 15:22 UTC
## Background

I did have a google project called `project-ci-1` , and i was using vault from another project `vault-project` , to manage Service Accounts in it through roleset. 

I had all the cross project IAM in place so everything was working great.

Then one day i swapped projects , so i deleted `project-ci-1` and created `project-ci-2` and later on changed the roleset in vault to point to the new project.

Since then i started to see , in my google cloud console for the vault-project , a 99.9% IAM Api errors.

After raising a case to google they provided me with the failed api which was indeed vault apparently still trying to delete the Service Account from project `project-ci-1` ... which now does not exist anymore.

Is this even possible / does it even make sense ? 

* Google was only able to give me a single example of a failed delete 
`DELETE /v1/projects/project-ci-1/serviceAccounts/vault-ci-key-1573117982@project-ci-1.iam.gserviceaccount.com?alt=json&prettyPrint=false HTTP/1.1` ... after many weeks of back and forth so i do not necessarily trust this is the issue ... even though it make sense 
* I can't see any error in Vault ( even with tracing enabled) to tell me is trying and failing to delete this service account , looking at the [code](https://github.com/hashicorp/vault-plugin-secrets-gcp/blob/056366f0562f4dcfdca0e9e3882f49bcb3eb4658/plugin/rollback.go#L219) it should 
* I looked into every possible leftover lease and i did find one that was matching the date i actually changed the roleset in the gcp secret backend , i revoked that using `vault write sys/leases/revoke lease_id=xxxx` ... but i can still see the errors in the api 

So i am starting to wonder if i am just looking in the wrong direction 

thanks !

**Comment by primeroz** [comment] 2020-03-23 10:51
as a quick follow up i was able to stop the issue by `disabling` and `re-enabling` the gcp secret mounted backend.

That to me prove that the issue was actually true even though no logs were being shown , maybe because trying to delete an SA from a project that does not exist causes an error not caught up by the log event ?

while i understand that i caused the issue by deleting the project before changing the vault gcp secret roleset configuration ... this can get the backend in a state that is quite hard to recover from

**Comment by runonautomation** [comment] 2020-04-09 09:53
Following up on the issue. I confirm the issue is present, and it is related to entries rollback procedure (WAL) 
Basically you can see in /sys/raw/logical/<backend_id>/wal/<entry_id> that the values will be present with a date > 5 mins.

**Comment by runonautomation** [comment] 2020-04-09 10:09
The issue is that WAL entry does not get removed even in respective RoleSet is not present in the mounted backend, and Vault keeps trying to clean up the resources. Will try to get more details in upcoming days.

**Comment by runonautomation** [comment] 2020-04-21 08:24
import hvac
import os
import json 
cache_map = dict()
client = hvac.Client(os.environ['VAULT_ADDR'],
                token=os.environ['VAULT_TOKEN'])
def to_list(path):
    return client.list(path)['data']['keys']

def to_dict(path):
    return json.loads(client.read(path)['data']['value'])

print("Is authenticated: {}".format(client.is_authenticated()))
backends = to_list("sys/raw/logical")
for backend in backends:
    cache_map[backend] = dict()
    backend_keys = to_list("sys/raw/logical/{}".format(backend))
    for key in backend_keys:
        cache_map[backend][key] = dict()
        if "roleset" in key:
            rolesets = to_list("sys/raw/logical/{}/roleset/".format(backend))
            for roleset in rolesets:
                roleset_data = to_dict("sys/raw/logical/{}/roleset/{}".format(backend, roleset))
                cache_map[backend][key][roleset] = roleset_data
        if "wal/" in key:
            wals = to_list("sys/raw/logical/{}/wal/".format(backend))
            for wal in wals:
                wal_data =  to_dict("sys/raw/logical/{}/wal/{}".format(backend, wal))
                cache_map[backend][key][wal] = wal_data
    print(str("Done processing backend: {}".format(backend)))

print('############ ERRORS ############')
for backend in cache_map:
    for backendkey, backendvalue in cache_map[backend].items():
        if not "wal" in backendkey: continue
        for wal, walvalue in cache_map[backend][backendkey].items():
            if 'RoleSet' in walvalue['data']:
                if not walvalue['data']['RoleSet'] in cache_map[backend]['roleset/']:
                    pass
                    # Those can be deleted relatively safely
                    print("vault delete sys/raw/logical/{}wal/{}".format(backend, wal))
                else:
                    # Those can be deleted with caution
                    # print("vault delete sys/raw/logical/{}wal/{}".format(backend, wal))

**Comment by Valarissa** [comment] 2021-01-26 19:51
Just an update to this: I was able to address this issue in https://github.com/hashicorp/vault-plugin-secrets-gcp/pull/104 and cut a new release: 0.8.2 which has this problem solved. It handles the issue for both account and policy_iam WALs. It should be bundled and released with the next release of Vault, but if you need to, you can feel free to update the plugin standalone.

**Comment by Valarissa** [comment] 2021-02-16 19:41
I'm going to close this now as I believe this has been addressed at this point.

**Closed by Valarissa** 2021-02-16 19:41 UTC

**Comment by wobes** [comment] 2021-03-31 23:34
@Valarissa Things are looking good.  Upgraded to vault 1.7.0 which includes your change. My initial tests show that the service accounts are cleaned up in GCP and no WAL entries generated in `sys/raw/logical...`
