### ISSUE TITLE
Is it possible to use this secrets engine to generate credentials for Terraform Google provider?

### ISSUE THREAD

**Issue by rolyv** [hashicorp/vault-plugin-secrets-gcp#32] opened 2019-03-14 13:42 UTC
I think there's a lack of documentation on how best to leverage this secrets engine in conjunction with Terraform Google provider. I've seen examples of people just storing a service key json in Vault kv engine and just retrieving that from Terraform for use with the Google provider. It seems like AWS secrets backend has first-class support from the [Terraform Vault provider](https://www.terraform.io/docs/providers/vault/d/aws_access_credentials.html) for generating access credentials. How can/should this be done for GCP?

**Comment by emilymye** [comment] 2019-03-14 17:57
We could look into actually adding the credentials endpoints, but I think most people just use the [generic read](https://www.terraform.io/docs/providers/vault/d/generic_secret.html) against the GCP secrets endpoint:

Examples
provider "vault" {
   ...
}

# Preferred, since access_token has a set TTL
provider "google" {
  access_token = "${data.vault_generic_secret.gcp_tf_token.data["token"]}"
}

# Less preferred, TF doesn't make it easy to revoke this value
# I believe you have to do this manually
provider "google" {
  credentials = "${base64decode(data.vault_generic_secret.gcp_tf_key.data["private_key_data"])}"
}

data "vault_generic_secret" "gcp_tf_token" {
  path = "gcp/token/tf-roleset"
}

data "vault_generic_secret" "gcp_tf_key" {
  path = "gcp/key/tf-roleset"
}

I know someone else also contributed https://www.terraform.io/docs/providers/vault/r/gcp_secret_backend.html (which is not in the sidebar? weird) but I have yet to actually contribute anything to the Vault provider. I don't know if I'll have time to add first-class-support for this endpoint right now.

**Comment by emilymye** [comment] 2019-06-18 14:37
I'm going to close this issue as a duplicate of the issue in the Terraform provider - can't promise I'll get to it very soon, but feel free to track that issue!

**Closed by emilymye** 2019-06-18 14:37 UTC
